language: node_js
node_js:
  - "lts/*"
addons:
  sonarcloud:
    organization: "discipl" # the key of the org you chose at step #3

before_install:
  - sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

script:
  - npm run lint
  - npm test
  - npm audit
  # other script steps might be done before running the actual analysis

after_success:
  - npm run coverage
  - 'if [ ! -z "$SONAR_TOKEN" ]; then sonar-scanner; fi'
