language: node_js
node_js:
  - "lts/*"
addons:
  sonarcloud:
    organization: "discipl"

script:
  - npm run lint
  - npm test
  - npm audit

after_success:
  - npm run coverage
  - 'if [ ! -z "$SONAR_TOKEN" ]; then sonar-scanner; fi'
